### ISSUE TITLE
Corrections to PDF Manual

### ISSUE THREAD

**Issue by therealkitman** [countmodula/VCVRackPlugins#101]
Hi,

Just a few corrections to the PDF manual V2.2.0-2 for the Oscilloscope. 

On page 60 needs two corrections -

1. "At a scale of 2V/Division a signal that is 10Vp-p will span the full height of the display." With those settings a 10Vp-p trace will only cover 5 divisions. If you want the full 20 divisions you need to set 0.5V/Div.

2. "The Position knob sets the horizontal position of the trace." I think you meant the vertical trace, not horizontal.

Regards...

**Comment by AdamVerspaget** [comment]
Hi,  thank you for letting me know. I will update the manual for  then next release.
