### ISSUE TITLE
Oscilloscope Freeze Button

### ISSUE THREAD

**Issue by therealkitman** [countmodula/VCVRackPlugins#102]
Hi,
I found the action of the Freeze button out of character with the other latching buttons. It's a momentary button that latches a red lamp indicating a 'freeze'. 

I would recommend removing the red lamp and making the Freeze button itself latching with maybe a red coloured button when active. That would be more conspicuous as well.

For you consideration. 

Thanks.

**Comment by AdamVerspaget** [comment]
Hi,

Freeze on the oscilloscope is not a straight-forward on/off function. The click on the freeze button merely arms the action which is indicated by the freeze light turning green until the current trace completes at which point it turns red to indicate it is complete. This behaviour is more obvious at slower trace rates.
