### ISSUE TITLE
Oscilloscope Holdoff/Triggers

### ISSUE THREAD

**Issue by therealkitman** [countmodula/VCVRackPlugins#103]
Hi (again),

I find the action of the Holdoff feature sometimes annoying as I forget about it and I take a while to 'find' my trace manually.

Could the Holdoff actually be made optionally disabled (or removed) and the traces can be either triggered or just free running?

Thanks...

**Comment by AdamVerspaget** [comment]
Hi,

Sorry, having an option to bypass the hold-off would be the same as setting it to zero and I think it would confuse many other users.
