### ISSUE TITLE
FADE - fade in time control seems to be ignored

### ISSUE THREAD

**Issue by dtenenba** [countmodula/VCVRackPlugins#108]
Hello,

I was really happy to come across the FADE module because I had been doing my fade in and fade outs manually.

However, the module does not appear to fade in properly. When I press the START/STOP button, the signal is quite audible (if quieter than it eventually gets). I would have expected it to start from completely silent.

[Here](https://pubmisc.s3.amazonaws.com/fadetest.mpg) is a short video demonstrating the problem. I have the fade in time set to the maximum. You can see (on the scope), and hear, that the sound starts immediately (the video recording is triggered by me pressing START). 

[Here](https://pubmisc.s3.amazonaws.com/fadetest.vcv) is the patch.

I am using VCV Rack 2.2.2 and version 2.3.0 of the Count Modula plugin. 
This is on an M1 Mac running macOS 12.6 (Monterey).

Is there a way to get more control over the fade in envelope? I see on the expander there is an envelope output, but not an input....

Thanks!

**Comment by AdamVerspaget** [comment]
Hi, the module is functioning exactly as intended. The fade in starts a zero volume and increases linearly to maximum volume over the fade in time. It's probably the linear fade in that gives the impression of volume at the start. I've attached a patch that uses a slew limiter and a VCA to achieve something similar for you to compare.  [fadetestcompare.zip](https://github.com/countmodula/VCVRackPlugins/files/10505948/fadetestcompare.zip)
Click on the manual gate to start the fade in.

There is no facility to add an external envelope. It doesn't make sense to do that as the time knobs would have no control over the attack and decay so they would be out of sync with the gate/trigger signals that start and stop the record module.

There's no need to connect both the gate and the trigger output to the record module by the way. Either one will work.

I am working on a new fade module that has log/exp options for the fade in and out slopes. I have no idea when that will be available though.
