### ISSUE TITLE
Octet Sequencer only able to reset to zero state

### ISSUE THREAD

**Issue by prommln** [countmodula/VCVRackPlugins#115]
Hi. Im a big fan of Count Modula modules and love the Octet sequencer for randomish triggers. Theres the following problem on my end at least: The reset input is resetting the sequencers to the zero state every time if its a clock/8 input. Because of this the 8th step is always skipped while the first beat is always off bc its starting from the zero-step.

I checked the manual appendix which states that the "clock cycle[s need to] occur within 100uS of each other" for it to start at step one. This is definitely the case as it works with other Count Modula sequencers perfectly. Maybe this feature has been left out for the Octet? It just does not feel like this works as intended and of course limits the potential of the module.

Theres (hopefully) a gif attached which shows an Octet and the 8x16 Gate Sequencer next to each other. Both clock inputs are being fed by the /2 output from the Count Modula Clock Divider while the reset input receives the /4 output. You can see how the Gate Sequencer plays steps 1+2 and Octet plays 0+1.

![Rack_N1hff7bw5B](https://github.com/countmodula/VCVRackPlugins/assets/133668656/f450af2e-4fda-439a-bc67-f47bc13d6cdf)

This is on Rack version 2.3.0 with all recent updates. Thanks for all your hard work and these great modules. Count Modula is a must have for every VCV-user.

**Comment by AdamVerspaget** [comment]
Fixed in v2.5.0.
