### ISSUE TITLE
Color Picker & Mixer

### ISSUE THREAD

**Issue by Bit-Fiddler** [countmodula/VCVRackPlugins#120]
Sorry the title should be "Color Picker / new Mixer / new module"

Could you add a function to the color palette such that hovering over a cable and pressing the hotkey will change the color of the existing cable?

And secondly, could you make a simple mixer in the basic 4H format that is simply a mixer with no knobs?  Just the 8 inputs and 1 output (or whatever fits nice).   Maybe 2x   4->1 with pass on, so if the second input is not used it will be treated as an 8->1 (Or 2x3->1 / 6->1, just whatever fits).  the mixer you have now is just a bit large, and the attenuators while nice, are not always needed.  So, a simpler compact module would make for more aesthetic patches at times.   And yes, I know...  virtual rack, space does not matter.  But I still try to make them look nice even if it does not matter.  There are many other "brands" that have this exact module.  But again, aesthetics, I like it when I can get modules of the same "brand" to fill the rack space...   Maybe it is just OCD?

And Finally

I would like a new module that will do the following:

-knob to select voltage -10 - +10
-CV input for this knob
-CV inverter switch
-reset jack
-mode selector knob (trigger/toggle/gate/always on/latch)
-CV input to select mode
-output jack that will output the voltage based on the mode.
-trigger jack will accept either a trigger or gate no matter what mode is set.

basically, if the CV input is used it will just resend the CV voltage, and if no CV input is connected it will send the voltage selected with the knob.

if mode is trigger when a trigger/gate is received it will pulse the output voltage as a "trigger"

if the mode is toggle each consecutive trigger/gate will toggle the output on/off

if the mode is gate the output voltage will be sent as long as the gate is held high or in the case of a trigger activating the module a predefined gate length is sent (selectable with a knob?)

if mode is always on the voltage will be sent continuously unless a trigger/gate is received (trigger/Gate inverter)

if the mode is "latch" the voltage will be sent when a trigger/gate is received and will remain on until the mode is changed, or a reset trigger is received on the reset jack.

This will create a single module which will give several functions.

-constant voltage source
-switched voltage source with several switching schemes
-a latching gate
-Trigger/Gate inverter
-Trigger/Gate converter
-voltage inverter

It is possible to get all this by using multiple modules I know, but again...  The OCD / aesthetics.  It all fits together nice as a single module, as in it makes sense (at least to me) that it would all be on the same module.  And as mentioned I would like to keep the same branding / aesthetics on the patches.

If further information is needed, I am happy to talk in greater detail. but I think this gives the basic idea of what I am looking for.

**Comment by AdamVerspaget** [comment]
Hi.

Thank you for your suggestions. 

On the cable colour picker, I think changing cable colours with the mouse over a cable would get confusing for many people with the global keyboard shortcuts enabled accidentally changing cable colours. The ability to change cable colours is now built into rack via the context menu.

I do have a mixer similar to what you're after in the works, hopefully when it is released it will suit your needs.

Your other module idea seems really quite specific to your needs. Having had issues in the past with developing custom modules for people I'm afraid I will have to decline on this one.

Adam.
