### ISSUE TITLE
Feature Request: Lighten Blue Knob Indicator

### ISSUE THREAD

**Issue by jonheal** [countmodula/VCVRackPlugins#18]
On cheap monitors (like the one I am using right now), the blue pointer indicator on knobs is almost indistinguishable from the gray knob itself. Would you consider lightening it in hue a bit?

**Comment by AdamVerspaget** [comment]
I can certainly do that. I'll pop it in the next release.

**Comment by jonheal** [comment]
Thanks much!

**Comment by AdamVerspaget** [comment]
Release in v1.1.0
