### ISSUE TITLE
8 step sequencer

### ISSUE THREAD

**Issue by Eurikon** [countmodula/VCVRackPlugins#23]
Hi there, 
with "8 step sequencer" when the sequence length is set to an odd number, and the direction is starting from the end. when feeding the reset input with S&H signal, sometimes the starting position will be before the sequence length. 
ie: the reset triggers a step that should be out of boundary.

is this normal behavior?

**Comment by AdamVerspaget** [comment]
Hi, I'm not sure what you mean by "feeding the reset input with S&H signal). Can you attach a VCV patch file to this issue for me to look at?  I can tell you that if you reduce the sequence length and the sequencer is travelling in the reverse direction, it will continue from it's current position and will not jump to the new shorter length.

**Comment by Eurikon** [comment]
in this patch you will see the play position sometimes travel over step 8 , while step 8 is out of boundary in the length selector.

[8step-test.zip](https://github.com/countmodula/VCVRackPlugins/files/3428973/8step-test.zip)

**Comment by AdamVerspaget** [comment]
Thank you. I can confirm that this is an issue and will fix it in due course.

**Comment by AdamVerspaget** [comment]
I have found the issue and will include the fix in the next release.

**Comment by Eurikon** [comment]
Thank You!
