### ISSUE TITLE
Voltage Controlled Frequency Divider MkII - Inverted gates

### ISSUE THREAD

**Issue by WouterSpekkink** [countmodula/VCVRackPlugins#25]
**Intro**
I was playing around with the Frequency Divider MKII, which looks like a very useful tool for manipulating events. I found what I think is a bug by chance. I didn't test intensively, but the bug does not appear to occur in Legacy mode.

**Context**
I have a sequencer that outputs a gate signal in a Euclidean pattern. 

This gate sequence is fed into the Frequency Divider MKII. I use the Uni output and send it to the X-input of the VCV scope for monitoring. I fed the original input of the sequencer to the Y-input of the VCV scope for comparison.

I then manipulate the *Manual* knob of the Frequency Divider MKII and monitor the VCV scope module to see how that affects the gate pattern.

**The bug and how to reproduce it**
In brief, the bug is that when first dialling the *Manual* knob up, and then dialling it down, the gate signal is sometimes inverted. It does not happen every time, so I guess it might have something to do with whether the gate signal is high or low when the *Manual* knob is dialled down again. That last bit is just speculation, of course.

The gate signal remains high even if the clock is stopped, or the input of the Frequency Divider MKII is unpatched. It is as if something is flipped incorrectly, and it stays that way.

**Comment by AdamVerspaget** [comment]
Hi, I would expect this behviour based on how the underlying divider works as you'll be transitioning  through odd divisions (which the old version did not do) and depending on what phase the input is at when the shift down occurs will cause the underlying counter to become out of sync. I don't think there's much I can do about it but take take a look at it anyway.

**Comment by WouterSpekkink** [comment]
Ah, okay, that sounds tricky then. That is a shame, because I was really hoping to use this to change the divisions live (although I could of course just use legacy mode). Is it maybe a way for the module to tell what phase it is in, and to postpone a downshift until the next 'right' phase appears? So, basically you would be priming the downshift by turning the knob, but the actual shift doesn't occur until it is in the phase that doesn't cause issues.

**Comment by AdamVerspaget** [comment]
I haven't forgotten about this. I am trying to think of a solution that will work for you and keep the existing functionality intact as I suspect holding off the downshift is going to mess with the division ratios. I am thinking perhaps a dedicated voltage controlled gate divider module may better suit your purpose rather than trying to shoehorn the functionality into the VC divider.

**Comment by WouterSpekkink** [comment]
Thanks, Adam. I appreciate your work on this, and I also understand that my request turns out to be a bit more complicated than I imagined.

**Comment by AdamVerspaget** [comment]
Hi Mate, what operating system are you running on? I have a new VC Gate Divider module that you can try out if you're on Windows (I don't have the means to compile binaries for Linux or Mac I'm afraid).

**Comment by WouterSpekkink** [comment]
Hi! Thanks for this! I run VCV on Windows. However, I am currently in the middle of moving countries, so I won't be able to try anything out until the end of August.

**Comment by AdamVerspaget** [comment]
Oh, OK. I might hold pop that module into the next release then as I would really like to see that it does the job correctly first. Good luck with your move.

**Comment by AdamVerspaget** [comment]
A voltage controlled pulse divider will be available in v1.6.0 that should be more conducive to dividing gate and trigger pulses.
