### ISSUE TITLE
Fade option request

### ISSUE THREAD

**Issue by vcvrackideas** [countmodula/VCVRackPlugins#39]
Hey mr. Count! Fade is a great module indeed
![2019-10-29_16-03-02](https://user-images.githubusercontent.com/42435368/67769483-9f22a700-fa65-11e9-890d-035d953b6f14.png)
, I has been waiting for this one for a while. But here is another request. Let's imagine the workflow - trig and gate now for stop mode will fire only when fading will be finished. It's obviously OK and must for record module. But for get proper fade out I have to stop the clock at first and then record module will record all the fades of tracks and reverb\delay tails and then stops completely when Fade module will say to it. So my request is adding an additional instant trigger out when user stops the Fade. 
I have tried already doing it through adding the additional trigger and mapping but have no luck.
Cheers and thanks for your innovative solutions for VCV!

**Comment by AdamVerspaget** [comment]
I like that idea. I might implement it as an expander though as I think we'll also need a gate output that follows the state of button rather than the envelope for those modules that use a gate to controll their run cycle rather than a start/stop pulse.

**Comment by AdamVerspaget** [comment]
Pending release in V1.5.1
