### ISSUE TITLE
Printable Manual

### ISSUE THREAD

**Issue by DaubRidArt** [countmodula/VCVRackPlugins#41]
Hey Count, any chance of a printable (A4?) or pdf manual? Current version is highly informative but a little cumbersome to navigate. (love these modules)

**Comment by AdamVerspaget** [comment]
Hi, thank you! I will be looking at improving the manual at some point in the future as it is becoming a bit hard to mange now that there are so many modules. I'm not sure exactly when I will be able to get to it though. Maybe over the Christmas period.

**Comment by DaubRidArt** [comment]
Good morning Adam,
Thanks for the reply. If I can be any help with it please let me know. I am a graphic designer as well as a VCV user and would be happy to get involved.
Do let me know what you think, incidentally, I’m not after a fee, I just like your modules and want to help.

Regards

Paul ®

**Comment by AdamVerspaget** [comment]
Thank you Paul that is very kind. I will bear it in mind.

**Comment by AdamVerspaget** [comment]
From V1.6.0, the user manual will be provided as a pdf downloadable from github.

**Comment by NickLarsenNZ** [comment]
Could it also be in markdown for easier viewing in Github?
