### ISSUE TITLE
Make Chances polyphonic (enhancement request)

### ISSUE THREAD

**Issue by bgracie** [countmodula/VCVRackPlugins#42]
Currently there are no poly Bernoulli gates in Rack

**Comment by AdamVerspaget** [comment]
Hi, thank you for the request. I did think about making it poly but there are some complexities need to be thought through first - handling of the CV input, display of the which gate outputs have been chosen etc.  I will see what I can do in release 1.8.0 though.

**Comment by bgracie** [comment]
Cool, thanks for your work on the plugin!

**Comment by AdamVerspaget** [comment]
Released in v1.8.0

**Comment by bgracie** [comment]
thanks!
