### ISSUE TITLE
VC Switch doesn't respond to polyphonic CV

### ISSUE THREAD

**Issue by glocke01** [countmodula/VCVRackPlugins#44]
VC switch is controlled only by the first channel of its CV input, even with the signal input is polyphonic.
![VC_switch_poly_bug](https://user-images.githubusercontent.com/12255580/73788577-3d13c500-476b-11ea-8025-ee5da62b9d8f.png)

**Comment by AdamVerspaget** [comment]
Yep, that's correct. It's not a polyphonic module as such but can switch polyphonic signals. Even says so in the manual. "This module can process polyphonic signals. All channels are switched by the same control voltage."

**Comment by glocke01** [comment]
thanks for the response. your collection is full of awesome.

**Comment by AdamVerspaget** [comment]
Thank you! Apologies if my response was tad terse, it wasn't meant to be. The good news is that there will be some polyphonic updates in the next release (v1.8.0) and I'll make sure there is a properly polyhonic VC switch in there.

**Comment by glocke01** [comment]
Looking forward to it! Thanks for all your hard work!!!!
