### ISSUE TITLE
Add Volume CV to Shepard Generator 

### ISSUE THREAD

**Issue by neonpixii** [countmodula/VCVRackPlugins#45]
For a Shepard tone illusion to work, low notes need to fade in from a quiet volume, and high notes need to fade out, so that middle tones are the most prominent (see https://en.wikipedia.org/wiki/Shepard_tone)

As it currently stands, i can find no simple or obvious way to get the output from Shepard Generator to conform to this loudness distribution, and Shephard Generator itself does not have any useful outputs for this purpose. 

My proposal is a polyphonic CV output underneath each of the 2 poly outputs, and a monophonic CV output adjacent to each of the mono outputs, which generates CV on a curve alongside the pitch outputs, so that it starts at zero when the pitch is lowest, gradually reaches a peak at the midpoint of the pitch progress (as determined by the Level knobs), and then fades out to zero as the pitch reaches its highest point

I'm unsure if a linear or exponential volume curve would be best for the illusion, and perhaps adding a dial to adjust the curve from linear to exponential would be the best course of action.

Regardless, adding volume control outputs would make the Shepard Generator a lot more usable. 

Thank you for making such a great module pack!

**Comment by AdamVerspaget** [comment]
Hi, thank you for your compliments.

The shepard generator merely provides two correctly phased unipolar signals, a saw for the pitch and a triangle for the volume. It does need to be connected correctly to other modules to achieve the shepard function.  Note that if you go too aggressive on the pitch change or to fast with the modulation the effect does not work that well.

Please have a look at the attached patch which functions correctly to my ears. 
[Shepard.zip](https://github.com/countmodula/VCVRackPlugins/files/4217853/Shepard.zip)

Let me know if this helps.
