### ISSUE TITLE
MUTE - muted state always reinitializes to 0 on loading a saved patch

### ISSUE THREAD

**Issue by mblofeld** [countmodula/VCVRackPlugins#51]
To reproduce:

Create patch with only the MUTE module
Click the mute button to set the mute state to 1
Save the patch.
Reopen the patch
mute state has returned to 0 

This module would be very useful as a standard highly visible master mute right before the Audio output but not if the mute state always returns to 0 (off)

**Comment by AdamVerspaget** [comment]
Hi, Thanks for letting me know. This will be fixed in the next release.

**Comment by AdamVerspaget** [comment]
Released in v1.11.0
