### ISSUE TITLE
Super arpeggiator sees only Channel 1 at poly input

### ISSUE THREAD

**Issue by vogelscheiss** [countmodula/VCVRackPlugins#53]
Applying a 4-note polyphonic input to the V/Oct in, but only Channel 1 appears in the status box. Have also tried with 8 notes, etc., still just Channel 1.

Obviously you can't arpeggiate just one note, so clearly something is going wrong for me here.

Is this a bug, or am I doing something wrong? Thx.

--Chuck

**Comment by AdamVerspaget** [comment]
Hi Chuck, the arpeggiator is actually driven by the number of gate channels not the number of CV channels. if you supply 1 gate, it will only look at the first CV channel, 2 gates the first 2 CV channels etc.

**Comment by vogelscheiss** [comment]
Adam – thanks, got it, makes sense. Resolved.
