### ISSUE TITLE
Super Arpeggiator: Change notes during hold state?

### ISSUE THREAD

**Issue by jonheal** [countmodula/VCVRackPlugins#55]
Good Count, sir,

Is it possible to change the behavior of the Hold button so that it holds the notes, but also loads with new notes and holds those instead if you press new keys on the keyboard?

**Comment by AdamVerspaget** [comment]
Hi, I'm not really sure that is possible as the hold function is essentially just a sample and hold that is triggered by the off to on  transition of the hold button (or the hold input). Detecting the new notes after the initial sample may be difficult especially if you have the midi module set to re-use previous channels. I'll have to have a bit more of think about it.

**Comment by jonheal** [comment]
Somehow, BOGAUDIO does it with his arpeggiator, but yours has many more features. Are you saying if I select a different setting in the MIDI-CC module, I might see different results?
  
 Anyway, love your stuff, and you're very prolific. :-)
  

--   Jon Heal   http://www.theheals.org/ 
 Have a nice day!  

  

----------------------------------------

**Comment by AdamVerspaget** [comment]
I wouldn't expect the Super Arpeggiator to behave differently at the moment as it takes a snapshot of the inputs when hold is engaged, I was thinking more about how it would behave if I updated it to allow new notes to be added as the channel ids of the input signals are integral to the core functionality. I also have to think about how it would behave when it is set to poly output mode too.

I'll leave this here as a wish-list item for the moment.

**Comment by jonheal** [comment]
Thanks for your consideration. I’m getting better at hitting the button with one hand while I press keys with the other, so maybe a non-issue eventually. 😊

**Comment by jonheal** [comment]
You can close and disregard this request, at least as far as I am concerned. I'm using VCV Chord to make notes instead of the keyboard (which I am a spaz with anyway), and it works perfectly. :)

https://community.vcvrack.com/t/count-modular-super-arpeggiator-and-vcv-chord/10665

**Comment by AdamVerspaget** [comment]
Glad you found a solution.  Thanks for letting me know.
