### ISSUE TITLE
light strip request

### ISSUE THREAD

**Issue by XtremeSounds** [countmodula/VCVRackPlugins#58]
very cool. can we get something horizontal and wider that we can run across the entire top of vcv like a lightbar. Im trying to use it with strip and make it strobe to the music. If there was a way to add a glow effect that emanated from the light itself that would be something also.  cool

**Comment by AdamVerspaget** [comment]
Hi. Thank you. I'm not sure exactly what you're asking for here. A single module that can span a variable number of HP with a horizontal bar of light across it or a bar of light that can be placed anywhere. Either way I really don't think anyone else is going to use a feature like this to be honest.
