### ISSUE TITLE
Binary Sequencer - Reset/run not working

### ISSUE THREAD

**Issue by espenstoro** [countmodula/VCVRackPlugins#6]
Hi.
Enjoying this module a lot, but it seems that whenever something is plugged into run/reset, it won't run at all. It'll receive a reset signal, but won't run, just jumps back to 0v, apparently.

I'm on Rack 0.6.2c, Windows 8.

**Comment by AdamVerspaget** [comment]
Hi,  yep that is correct behaviour. it requires a high at the run input to run and resets on the positive going edge of the run signal. It operates like a gate.

**Comment by AdamVerspaget** [comment]
In the next release the reset and run functions will be split into separate jacks which should give you the reset behaviour  you're looking for.
