### ISSUE TITLE
Gate & Trigger sequencer outputs

### ISSUE THREAD

**Issue by blackearth2014** [countmodula/VCVRackPlugins#68]
Adam,

I have noticed that your gate sequences and trigger sequencer Gate & Trigger outputs are the same lengths. There is no perceivable difference between the two. Is that right?

**Comment by AdamVerspaget** [comment]
Hi  mate, yep that's right. The trigger outputs on both the gate and trigger sequencers preserve the width of the incoming clock by design. The Gate outputs on the gate sequencer will be the full width of each step.
