### ISSUE TITLE
Slope Detector: Minimum required slope?

### ISSUE THREAD

**Issue by jamshark70** [countmodula/VCVRackPlugins#69]
I'm generating slow linear ramps (in a Pd script running in VCV prototype). I was hoping to use Slope Detector to tell when the signal switches from falling (or steady) to rising.

However, most of the time, "rising" is not detected unless I set the ramp time to be much shorter than I want. (It seems also to be related to the absolute signal level -- the same linear slope isn't detected at low voltages, but is detected at higher voltages.)

I did set slope range to "slow."

So I'm curious what the threshold is. (Whatever it is, it seems like I need slower than "slow.")

**Comment by AdamVerspaget** [comment]
Hi, the slope detector works by comparing a slewed voltage against the original. If there is difference of > 0.01 volt between the two  then the slope is detected. It is really designed for use with envelope generators etc to allow gates to be generated for each stage.
