### ISSUE TITLE
Polyphony for Gate Modifier

### ISSUE THREAD

**Issue by snailtoe** [countmodula/VCVRackPlugins#70]
I'm a big fan of the Gate Modifier, it does exactly what I need it to do but I need eight of them doing it at once. Is there a possibility that polyphony could be added to it? Initially I was just thinking so it could handle several gate in/outs with the same length for all of them but once I allowed myself to keep making wishes I wondered if it could handle a polyphonic input on the CV too so that they could each handle different settings? I appreciate that asking for more when you've already given so much is greedy... but yet here I am! Thanks

**Comment by AdamVerspaget** [comment]
Hi, thank you for the request. I'll have a think about the best way to implement this for v1.16.0.

**Comment by snailtoe** [comment]
Thanks, I realised after posting this just how efficient Gate Mod is and that it doesn't really use any CPU so it's purely an aesthetic request at this point!

**Comment by AdamVerspaget** [comment]
New Poly Gate Mod module had been added to v1.16.0. Currently with the library team for build.
