### ISSUE TITLE
Other divisions for the clock divider

### ISSUE THREAD

**Issue by omricohenmusic** [countmodula/VCVRackPlugins#73]
Hi!

It would be great to have more options for the clock divider for different divisions like 3, 5, 6, 7, 9, and so on. Maybe with a switch like the Doepfer one, or something in the right-click menu.

Thanks so much!

**Comment by AdamVerspaget** [comment]
Yep, this has been on my todo list for a while. Look for it the next release.

**Comment by omricohenmusic** [comment]
Thank you so much, Adam!On Sep 16, 2021 13:26, AdamVerspaget ***@***.***> wrote:
Yep, this has been on my todo list for a while. Look for it the next release.

**Comment by AdamVerspaget** [comment]
Clock Divider module has been expanded with extra division modes in v1.16.0. Currently with the library team for build.
