### ISSUE TITLE
Attenuator Channel A Problem

### ISSUE THREAD

**Issue by Telerex** [countmodula/VCVRackPlugins#78]
I appear to be the first to raise this.
When using channel A on the attenuator with no input, the control knob has no effect on the output in attenuation mode. The channel continues to output the last voltage from the attenuverted mode. Everything is fine with an input signal connected.
Hopefully an easy fix. Thanks.

**Comment by AdamVerspaget** [comment]
Hi, thanks for letting me know. 
This has been fixed in V2.
