### ISSUE TITLE
default theme colour not persistent in browser

### ISSUE THREAD

**Issue by Eurikon** [countmodula/VCVRackPlugins#80]
Hi, firstly thanks for your fantastic plugin, and for continuing it into the V2 realm!
I wanted to ask you about the theming of this plugin. 

With other plugins that provide the option for changing and saving the default theme colour,
those plugins represent their module screenshots in the browser in the saved default colour. 

ie: when the plugin its default is set to dark themed, the modules show up as dark themed in the browser. 

Some plugins with such behaviour: 
Impromptu
Bogaudio
Geodesics
Surge
Submarine

Would be really nice if your modules followed this behaviour as well.

Cheers!
Latif

**Comment by AdamVerspaget** [comment]
Default theme is now being used in the browser however due to the fact that the browser caches the module when the application loads and does not refresh it, any changes to the default theme will not be reflected until the application is next started. This is the same for the other plugins I tried.
