### ISSUE TITLE
feature request

### ISSUE THREAD

**Issue by gharrus** [countmodula/VCVRackPlugins#81]
Dear Count Modula,

A few months back, I expressed the wish there were 4 or 5 digits to the Event Timer (https://community.vcvrack.com/t/count-modula-event-timer-4-digits-instead-of-3/12474/7). It was then a mere wish, now I believe it could be a feature request - I would say a reasonable wish.

Could you add it to your "new feature" list [edit: 5 digits preferred]?

Thanks in advance 

Gilbert
PS: if you are curious, you can check at https://soundcloud.com/suno-san/sets/dedicated-to-steve what I did in the past with event timer.

**Comment by AdamVerspaget** [comment]
This will be available in v2.2.0.

I have renamed the Event Timer to "Countdown 3" and added the new one as Countdown 5".

Also added a retrigger option to allow it to be restarted by the trigger pulse if it has not yet reached zero.

![image](https://user-images.githubusercontent.com/49931541/163737885-37389182-8574-4714-9390-801ce4191ca4.png)

**Comment by gharrus** [comment]
Thanks! Envoyé de mon mobile 
-------- Message d'origine --------De : AdamVerspaget ***@***.***> Date : 18/04/2022  02:30  (GMT+01:00) À : countmodula/VCVRackPlugins ***@***.***> Cc : gharrus ***@***.***>, Author ***@***.***> Objet : Re: [countmodula/VCVRackPlugins] feature request (Issue #81) 
Closed #81.

**Comment by gharrus** [comment]
Great, thanks Envoyé de mon mobile 
-------- Message d'origine --------De : AdamVerspaget ***@***.***> Date : 18/04/2022  02:30  (GMT+01:00) À : countmodula/VCVRackPlugins ***@***.***> Cc : gharrus ***@***.***>, Author ***@***.***> Objet : Re: [countmodula/VCVRackPlugins] feature request (Issue #81) 
This will be available in v2.2.0.
I have renamed the Event Timer to "Countdown 3" and added the new one as Countdown 5".
Also added a retrigger option to allow it to be restarted by the trigger pulse if it has not yet reached zero.

**Comment by gharrus** [comment]
Thanks indeed ! Downloaded and using it.

Gilbert
