### ISSUE TITLE
random hotkey for sequencers

### ISSUE THREAD

**Issue by XtremeSounds** [countmodula/VCVRackPlugins#83]
Hi it would be great if we could assign a hot key to random the cv of the 8 step sequencer.  In vcv rack we can press ctrl R to randomize all parameters but I would only be interested in randomized the sequence itself. Or even having some random buttons on the face would be good rather than menu diving this one.

**Comment by AdamVerspaget** [comment]
Will be included  in v2.2.0.
Hot keys as follows:
- Shift+Ctrl+R = Randomise CV + Gates/Triggers
- Shift+Ctrl+C = Randomise CV only
- Shift+Ctrl+T = Randomise Gates/Triggers only

Modules updated:
- 8 Step Sequencer +  channel expander
- 16 Step Sequencer +  channel expander
- 8 Step Basic Sequencer
