### ISSUE TITLE
Connecting VCV MIDI to CV V/OCT to Count Modula SuperArpeggiator V/OCT hangs Rack 2 Pro VST in Bitwig on Windows 

### ISSUE THREAD

**Issue by pgatt** [countmodula/VCVRackPlugins#84]
Bitwig 4.1.2 build 2021-12-14
Windows 10 Pro
VCV Rack 2 Pro 2.0.4 and 2.0.5
RME Babyface running latest firmware and totalmix

Connecting the V/Oct of midicv to V/Oct of CM Super Arpeggiator immediately hangs the process. Killing it terminates the Bitwig plugin host but allows restart of Bitwig's audio engine.

User initially thought it was related to polyphony, but seems to happen with any setting (mono, etc.) 
Doesn't happen in the standalone VCV2 Pro.

**Comment by AdamVerspaget** [comment]
I am unable to replicate this issue using Waveform 11 ( I don't have Bitwig).

**Comment by pgatt** [comment]
Sorry Adam, I just got confirmation that it was connecting to the Super Arpeggiator's HOLD input not the V/Oct input. User accidentally connected to the HOLD input and it crashes.

**Comment by AdamVerspaget** [comment]
No worries Paul.  I still cannot replicate the issue in my DAW. There was an odd thing happening around the hold button/input that was causing the button to not enable the hold properly which I have just fixed (Issue #85). Maybe the issue was related to that.

**Comment by AdamVerspaget** [comment]
Closing as I have not been able to replicate the issue.
