### ISSUE TITLE
Super Arpeggiator programme and hold buttons not working

### ISSUE THREAD

**Issue by MaZe6K** [countmodula/VCVRackPlugins#85]
The "PROGRAMME" buttons on the Super Arpeggiator are not clickable for me and the Hold button clicks and lights up, but doesn't hold the chord.

I'm on Windows 10, Rack 2.0.5, Count Modula 2.0.2

**Comment by MaZe6K** [comment]
Oh... Programme only works in Programme mode... so, sorry, false alarm... but hold still doesn't seem to work... maybe I'm doing something else wrong here...

**Comment by AdamVerspaget** [comment]
Will be fixed in the next release. A workaround until then is to use an external manual gate module connected to the hold CV input.
