### ISSUE TITLE
FADE feature request

### ISSUE THREAD

**Issue by omricohenmusic** [countmodula/VCVRackPlugins#88]
Hi Adam!

I'm pretty sure there's nothing to do about it but it would be great if there would be a way to externally trigger the FADE module. There's no space on the module anymore though so I'm pretty sure there's no way of adding this, but it could be fun for generative patches, and for not using the mouse. 

Thanks again!

**Comment by AdamVerspaget** [comment]
Hi Omri, I'll see what I can do. I can't make any promises though; as you say, the panel is already quite full.

**Comment by omricohenmusic** [comment]
I appreciate it, Adam, thank you!
________________________________

**Comment by AdamVerspaget** [comment]
OK, after a bit of fiddling around, I have come up with this possibility:

![image](https://user-images.githubusercontent.com/49931541/156697025-3731afc9-e53e-4481-9c03-44d243c3b572.png)

The CTRL Input will accept either a gate or a start/stop trigger sequence depending on the user selected configuration (option in the context menu). The Start/Stop button will be disabled if there is a cable connected to the CTRL input.

**Comment by omricohenmusic** [comment]
That looks like a great solution, thanks so much!
________________________________

**Comment by AdamVerspaget** [comment]
Released in v2.1.0
