### ISSUE TITLE
Proposal on MiniOctet Seq.

### ISSUE THREAD

**Issue by firolightfog** [countmodula/VCVRackPlugins#89]
I'd like to propose a new monophonic module. It is the smaller (and simpler) version of the great [Octet Trigger Sequencer](https://library.vcvrack.com/CountModula/OctetTriggerSequencer).

As much as I love the concept of Octet Sequencer I find it hard to work with it. This simple 1x16 trigger sequencer would allow creation of trigger patterns just like its bigger brother the [Octet Trigger Sequencer](https://library.vcvrack.com/CountModula/OctetTriggerSequencer). The four stepped knobs have a range of 0-15 all representing a unique 4-step sub pattern. The four inputs have a range of 0V-10V and converted to 0-15 value. 

![image](https://user-images.githubusercontent.com/34127628/152519419-1f86f1bf-1946-4c43-8b9c-63040a73c4c0.png)

Due to the similar structure it could use [Octet Trigger Sequencer CV Expander](https://library.vcvrack.com/CountModula/OctetTriggerSequencerCVExpander) and [Octet Trigger Sequencer Gate Expander](https://library.vcvrack.com/CountModula/OctetTriggerSequencerGateExpander). The main benefit of this module would be the added usability. It looks dead simple. And it is dead simple.

**Comment by S0210** [comment]
But actually any kind of variation of the original [Octet Trigger Sequencer](https://library.vcvrack.com/CountModula/OctetTriggerSequencer) would be great fun. It's such a great concept to quickly create some patterns. Just look this no-knob version with a 1x32 pattern. 

Your modules always take me daydreaming... 

![image](https://user-images.githubusercontent.com/34127628/152524652-6b2a4ceb-60a1-429a-b7cb-6661fb70e773.png)

**Comment by AdamVerspaget** [comment]
I will be going with the first option but adding attenuverters to the CV inputs.

![image](https://user-images.githubusercontent.com/49931541/156697950-e0f440fb-c490-4cc4-80ee-9862031a7557.png)

It will work the two Octet Sequencer Expanders which, when connected to the Nibble sequencer, will function like they do when connected to the Octet sequencer in linked mode.

**Comment by AdamVerspaget** [comment]
Released in v2.1.0
