### ISSUE TITLE
Matrix Mixer CV source mode not working

### ISSUE THREAD

**Issue by DaveBenham** [countmodula/VCVRackPlugins#91]
The documentation states "The first input channel (top row) acts as a CV 
source if no cable is plugged into the jack". This feature is not working for me on Windows 10. Output is always 0V no matter how I set any of the knobs if there are no inputs.

**Comment by AdamVerspaget** [comment]
How on earth did I screw that up!  I'll fix it in the next release.

**Comment by AdamVerspaget** [comment]
Will be released in v2.2.0. Fix is available in the v2.2.0 branch on github.
