### ISSUE TITLE
Gated Comparator enhancement - option to XOR looped input

### ISSUE THREAD

**Issue by DaveBenham** [countmodula/VCVRackPlugins#94]
For the Gated Comparator, currently the looped input is ORed with the comparator input.

It would be great if there was an option to use XOR instead. There is plenty of room next to the loop controls to add a switch or button to select OR or XOR.

XOR is cool because if the comparator input is constant low, then the 8 steps are looped as is. If high, then the sequence becomes 16 steps, with the second set of 8 being the logically inverted values.

With the XOR option, your module could function as a Benjolin rungler!

**Comment by AdamVerspaget** [comment]
Added panel switch giving options OR/AND/XOR logic on the loop input. Also tweaked the performance a little bit.
Will be released in v2.2.0

**Comment by DaveBenham** [comment]
Fantastic!
