### ISSUE TITLE
Hyper Manical LFO Expander does not honor the bi/uni setting set on main module

### ISSUE THREAD

**Issue by fractalgee** [countmodula/VCVRackPlugins#97]
Rack 2.12, MacOS 13.0, v 2.2.0 of Count Modula plugin. 

Attached patch shows that the expander ignores the main modules setting for bi/uni LFOs.  Remove .zip suffix, just added to archive name due to git not liking .vcv archives.  Start the polyrhythmic Clock top left, second module next to reset. I would need to stick 6 attenuverters in-between to get them all uni or bi, if main is set differently, should the expander not honor main module's setting? Or at least provide the option in right-click menu (more flexible but less intuitive)

[FG_R2_126_04_Bridges_Fun.vcv.zip](https://github.com/countmodula/VCVRackPlugins/files/9869593/FG_R2_126_04_Bridges_Fun.vcv.zip)

**Comment by AdamVerspaget** [comment]
Hi. The expander was never intended to have unipolar output but I'll see if I can find a good way to implement it without breaking existing patches.

**Comment by fractalgee** [comment]
would it not be best to have it honor the main module setting? Maybe make
it a right-click menu option to follow the main's setting, that way
everything will stay same if not enabled. I just feel that is the intuitive
way to use any expander.....

Thanks!

**Comment by AdamVerspaget** [comment]
I've added a context menu item that lets you select Bipolar, Unipolar or Follow LFO for the output mode. If you select "Follow LFO", the outputs follow the button on the LFO. You can select this and save a default preset to have it enabled every time you add a new expander.  This will go into the v2.3.0 release; not sure when that will be though.

**Comment by fractalgee** [comment]
Perfect Adam, thanks!
