### ISSUE TITLE
Expander visibility from right-click menu

### ISSUE THREAD

**Issue by omricohenmusic** [countmodula/VCVRackPlugins#99]
Hi Adam!

Will it be possible to add the option in the right-click menu of the different modules to add the respective expanders? For example, instead of looking for the expander for the Euclidean sequencer, it will be possible to add it from the right-click menu of the sequencer itself. That way, there's no need to scroll and search for the different expanders. 

Thanks so much!

**Comment by AdamVerspaget** [comment]
Hi Omri, I'll see what I can do. It will depend on whether or not I can traverse the list of already connected expanders to find the right-most one as most of them can be stacked side by side. There could be 3 CV expanders to the right of the master module and I may not be able to locate the last one on the right from the master:

![image](https://user-images.githubusercontent.com/49931541/209112761-792d6b4c-0345-4bed-aa29-733c73fe0a1e.png)

I suppose I could add the functionality to the expanders too. You would click on the right most expander and select "Add another expander" to add the expander.

**Comment by AdamVerspaget** [comment]
Will be included in v2.3.0

**Comment by omricohenmusic** [comment]
Hi Adam!

That's great, thanks so much and happy holidays!
________________________________
